#pragma config(UART_Usage, UART1, uartUserControl, baudRate9600, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartUserControl, baudRate9600, IOPins, None, None)
#pragma config(Sensor, dgtl1,  dir,            sensorDigitalOut)
#pragma config(Sensor, dgtl2,  step,           sensorDigitalOut)
#pragma config(Sensor, dgtl3,  enable,         sensorDigitalOut)
#pragma config(Sensor, dgtl4,  dir2,           sensorDigitalOut)
#pragma config(Sensor, dgtl5,  step2,          sensorDigitalOut)
#pragma config(Sensor, dgtl6,  enable2,        sensorDigitalOut)
#pragma config(Sensor, dgtl7,  dir3,           sensorDigitalOut)
#pragma config(Sensor, dgtl8,  step3,          sensorDigitalOut)
#pragma config(Sensor, dgtl9,  enable3,        sensorDigitalOut)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* -2 = EJE X */
/* -3 = EJE Y  */
/* -4 = EJE Z o punta lapiz */
/* -5 = Valores ajenos a ejes X, Y, Z */
/* -100 =  FIN DE COORDENADAS */

/* caracteristicas */
/* eje Y hace 1cm en 50 pasos , 1mm en 5 pasos , 0.2mm por paso
eje X hace 1cm en 63 pasos , 1mm en 7 pasos , 0.158mm por paso*/

float Xo = 0.0; float X = 0.0; float Z = 0.0;  //
float Yo = 0.0; float Y = 0.0;
float pen = 0.0;
/*
float tmppx = 87; // tiempo milisegundos por paso ejex
float tmppy = 110;   // tiempo milisegundos por paso ejey
*/
float tmppx = 5; // tiempo milisegundos por paso ejex
float tmppy = 5;   // tiempo milisegundos por paso ejey

// variables timer
int a = 0; int b = 0;
int c = 0; int d = 0;


 float vectorCoodenadas[]={-2,2.989792 ,-3,22.073966,-4,-1.000000,-2,2.989792 ,-3,3.183819 ,-4,-1.000000,-2,21.200291 ,-3,3.183819 ,-4,-1.000000,
-2,21.200291 ,-3,22.073966 ,-4,-1.000000,-2,2.989792 ,-3,22.073966 ,-4,-1.000000 ,-100}; //FIN VECTOR

//variables para leer coodenadas
int k=0; int j=0; int banx=1;int bany=1;

// variables para hallar catetos
float co=0.0; float ca=0.0;

// declaracion funciones
void Rectangulo(int ancho, int alto);
void pendiente(float x,float xo,float y,float yo);
void catetos(void);

int h=0; int h2=0;//borrar despues

task main()
{
	// Setup the two UART ports
	configureSerialPort(uartOne, uartUserControl);
	configureSerialPort(uartTwo, uartUserControl);
	setBaudRate(uartOne, baudRate9600);
	setBaudRate(uartTwo, baudRate9600);


	Rectangulo(10,10);
	//-------------------------loop--------------------------------
	k=0;
	while(1){ //loop

		//leer codenadas X,Y,Z
		j=0; Xo = X; Yo = Y;
		while(j<3){
			if      (vectorCoodenadas[k]== -2){ X = vectorCoodenadas[k+1];j++;}
			else if (vectorCoodenadas[k]== -3){ Y = vectorCoodenadas[k+1];j++; }
			else if (vectorCoodenadas[k]== -4){ Z = vectorCoodenadas[k+1];j++; }
			if(vectorCoodenadas[k]==-100){j=4;} //pone a j mayor a 3 para salir del while
			else{k++;}
		}
		pendiente(X,Xo,Y,Yo);
		//wait1Msec(2000);
		if (X>Xo){SensorValue[dir] = 0;} else{SensorValue[dir] = 1;}
		if (Y>Yo){
			SensorValue[dir2] = 0;
			SensorValue[dir3] = 0;}
		else{
			SensorValue[dir2] = 1;
			SensorValue[dir3] = 1;}
		//wait1Msec(3000);
		//--------Diagonal------------

		SensorValue[enable]=0; SensorValue[enable2]=0; SensorValue[enable3]=0;
		//SensorValue[dir] = 1; SensorValue[dir2] = 1;  SensorValue[dir3] = 1;
		ClearTimer(T1); ClearTimer(T2);
		catetos();
		h=0;h2=0;
		while(h<co || h2<ca){ // ||
			if (time1[T1] >= tmppx && banx==1){
				SensorValue[step] = 1; wait1Msec(1);
				SensorValue[step] = 0; wait1Msec(1);
				ClearTimer(T1);
				h2++;
			}

			if (time1[T2] >= tmppy && bany==1 ){
				SensorValue[step2] = 1; wait1Msec(1);
				SensorValue[step2] = 0; wait1Msec(1);

				SensorValue[step3] = 0; wait1Msec(1);
				SensorValue[step3] = 1; wait1Msec(1);
				ClearTimer(T2);
				h++;
			}

		}
		//wait1Msec(3000);
	}//loop
}//main
//-----------FUNCIONES-------------
void pendiente(float x,float xo,float y,float yo){
	tmppx = 5; tmppy = 5;
	float yy=0.0;float xx=0.0;
	yy=(y - yo); xx=(x - xo);
	if (xx==0){ tmppy = 1; banx=0;}else {banx=1;} //apaga eje si es cero
	if (yy==0){ tmppx = 1; bany=0;}else {bany=1;}	 //apaga eje y si es cero

	if (xx!=0 && yy!=0){
		tmppx = 5; tmppy = 5;
		pen = yy/xx;
		if (abs(pen)<1){ tmppy = tmppy/abs(pen); }
		else { tmppx = tmppx*abs(pen); }
	}
}
void catetos(void){

	co=0.0; ca=0.0;
	ca = abs(X)-abs(Xo); ca = abs(ca);
	co = abs(Y)-abs(Yo); co = abs(co);
	co = co/0.2; ca = ca/0.2; // numero de pasos para recorrer cada cateto

}
void Rectangulo(int ancho, int alto){ // ancho y alto en milimetros de un cuadrado

	SensorValue[enable]=0; SensorValue[enable2]=0; SensorValue[enable3]=0;
	SensorValue[dir] = 1; SensorValue[dir2] = 1;  SensorValue[dir3] = 1;
	//eje x
	SensorValue[dir] = 1;
	for(int i=0;i<5*ancho;i++){
		SensorValue[step] = 0; wait1Msec(1);
		SensorValue[step] = 1; wait1Msec(1);}
	// eje y
	SensorValue[dir2] = 1; SensorValue[dir2] = 1;
	for(int i=0;i<5*alto;i++){
		SensorValue[step2] = 0; wait1Msec(1);
		SensorValue[step2] = 1; wait1Msec(1);

		SensorValue[step3] = 0; wait1Msec(1);
		SensorValue[step3] = 1; wait1Msec(1);}
	//
	//eje x
	SensorValue[dir] = 0;
	for(int i=0;i<5*ancho;i++){
		SensorValue[step] = 0; wait1Msec(1);
		SensorValue[step] = 1; wait1Msec(1);}
	// eje y
	for(int i=0;i<5*alto;i++){
		SensorValue[dir2] = 0; SensorValue[dir3] = 0;
		SensorValue[step2] = 0; wait1Msec(1);
		SensorValue[step2] = 1; wait1Msec(1);

		SensorValue[step3] = 0; wait1Msec(1);
		SensorValue[step3] = 1; wait1Msec(1);}

}
